/**
 * Bangladesh upazilas — all 64 districts (selected upazilas appear as
 * direct dropdown options at checkout, owner request).
 *
 * Keys MUST match the `en` names in DISTRICTS (src/lib/sunamganj.ts).
 * Sunamganj keeps its Bangla-labelled list in SUNAMGANJ_UPAZILAS — this
 * module covers the remaining districts for courier orders.
 */

export const BD_UPAZILAS: Record<string, string[]> = {
  Sunamganj: [
    "Sunamganj Sadar",
    "Shantiganj (Dakshin Sunamganj)",
    "Balaiganj",
    "Bishwamvarpur",
    "Chhatak",
    "Derai",
    "Dharampasha",
    "Dowarabazar",
    "Jagannathpur",
    "Jamalganj",
    "Sullah",
    "Tahirpur",
  ],
  Sylhet: [
    "Sylhet Sadar",
    "Balaganj",
    "Beanibazar",
    "Bishwanath",
    "Companiganj",
    "Dakshin Surma",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",
    "Jaintiapur",
    "Kanaighat",
    "Osmani Nagar",
    "Zakiganj",
  ],
  Moulvibazar: [
    "Moulvibazar Sadar",
    "Barlekha",
    "Juri",
    "Kamalganj",
    "Kulaura",
    "Rajnagar",
    "Sreemangal",
  ],
  Habiganj: [
    "Habiganj Sadar",
    "Ajmiriganj",
    "Bahubal",
    "Baniyachong",
    "Chunarughat",
    "Lakhai",
    "Madhabpur",
    "Nabiganj",
    "Shayestaganj",
  ],
  Netrokona: [
    "Netrokona Sadar",
    "Atpara",
    "Barhatta",
    "Durgapur",
    "Kalmakanda",
    "Kendua",
    "Khaliajuri",
    "Madan",
    "Mohanganj",
    "Purbadhala",
  ],
  Kishoreganj: [
    "Kishoreganj Sadar",
    "Austagram",
    "Bajitpur",
    "Bhairab",
    "Hossainpur",
    "Itna",
    "Karimganj",
    "Katiadi",
    "Kuliarchar",
    "Mithamain",
    "Nikli",
    "Pakundia",
    "Tarail",
  ],
  Brahmanbaria: [
    "Brahmanbaria Sadar",
    "Akhaura",
    "Ashuganj",
    "Bancharampur",
    "Bijoynagar",
    "Kasba",
    "Nabinagar",
    "Nasirnagar",
    "Sarail",
  ],
  Cumilla: [
    "Cumilla Adarsha Sadar",
    "Cumilla Sadar Dakshin",
    "Barura",
    "Brahmanpara",
    "Burichang",
    "Chandina",
    "Chauddagram",
    "Daudkandi",
    "Debidwar",
    "Homna",
    "Laksam",
    "Meghna",
    "Monohorgonj",
    "Muradnagar",
    "Nangalkot",
    "Titas",
  ],
  Chandpur: [
    "Chandpur Sadar",
    "Faridganj",
    "Haimchar",
    "Haziganj",
    "Kachua",
    "Matlab Dakshin",
    "Matlab Uttar",
    "Shahrasti",
  ],
  Noakhali: [
    "Noakhali Sadar",
    "Begumganj",
    "Chatkhil",
    "Companiganj",
    "Hatiya",
    "Kabirhat",
    "Senbagh",
    "Sonaimuri",
    "Subarnachar",
  ],
  Feni: [
    "Feni Sadar",
    "Chhagalnaiya",
    "Daganbhuiyan",
    "Fulgazi",
    "Parshuram",
    "Sonagazi",
  ],
  Lakshmipur: [
    "Lakshmipur Sadar",
    "Kamalnagar",
    "Raipur",
    "Ramganj",
    "Ramgati",
  ],
  Chattogram: [
    "Chattogram Sadar (Pahartali/Double Mooring)",
    "Anwara",
    "Banshkhali",
    "Boalkhali",
    "Chandanaish",
    "Fatikchhari",
    "Hathazari",
    "Karnaphuli",
    "Lohagara",
    "Mirsharai",
    "Patiya",
    "Rangunia",
    "Raozan",
    "Sandwip",
    "Satkania",
    "Sitakunda",
  ],
  "Cox's Bazar": [
    "Cox's Bazar Sadar",
    "Chakaria",
    "Kutubdia",
    "Maheshkhali",
    "Pekua",
    "Ramu",
    "Teknaf",
    "Ukhia",
  ],
  Rangamati: [
    "Rangamati Sadar",
    "Bagaichhari",
    "Barkal",
    "Belaichhari",
    "Juraichhari",
    "Kaptai",
    "Kawkhali",
    "Langadu",
    "Naniarchar",
    "Rajasthali",
  ],
  Khagrachhari: [
    "Khagrachhari Sadar",
    "Dighinala",
    "Lakshmichhari",
    "Mahalchhari",
    "Manikchhari",
    "Matiranga",
    "Panchhari",
    "Ramgarh",
  ],
  Bandarban: [
    "Bandarban Sadar",
    "Ali Kadam",
    "Lama",
    "Naikhongchhari",
    "Rowangchhari",
    "Ruma",
    "Thanchi",
  ],
  Dhaka: [
    "Dhamrai",
    "Dohar",
    "Keraniganj",
    "Nawabganj",
    "Savar",
  ],
  Gazipur: [
    "Gazipur Sadar",
    "Kaliakair",
    "Kaliganj",
    "Kapasia",
    "Sreepur",
  ],
  Narayanganj: [
    "Narayanganj Sadar",
    "Araihazar",
    "Bandar",
    "Rupganj",
    "Sonargaon",
  ],
  Narsingdi: [
    "Narsingdi Sadar",
    "Belabo",
    "Monohardi",
    "Palash",
    "Raipura",
    "Shibpur",
  ],
  Tangail: [
    "Tangail Sadar",
    "Basail",
    "Bhuapur",
    "Delduar",
    "Dhanbari",
    "Ghatail",
    "Gopalpur",
    "Kalihati",
    "Madhupur",
    "Mirzapur",
    "Nagarpur",
    "Sakhipur",
  ],
  Mymensingh: [
    "Mymensingh Sadar",
    "Bhaluka",
    "Dhobaura",
    "Fulbaria",
    "Gaffargaon",
    "Gauripur",
    "Haluaghat",
    "Ishwarganj",
    "Muktagachha",
    "Nandail",
    "Phulpur",
    "Tarakanda",
    "Trishal",
  ],
  Jamalpur: [
    "Jamalpur Sadar",
    "Bakshiganj",
    "Dewanganj",
    "Islampur",
    "Madarganj",
    "Melandaha",
    "Sarishabari",
  ],
  Sherpur: [
    "Sherpur Sadar",
    "Jhenaigati",
    "Nakla",
    "Nalitabari",
    "Sreebardi",
  ],
  Bogura: [
    "Bogura Sadar",
    "Adamdighi",
    "Dhunat",
    "Dhupchanchia",
    "Gabtali",
    "Kahaloo",
    "Nandigram",
    "Sariakandi",
    "Shajahanpur",
    "Sherpur",
    "Shibganj",
    "Sonatala",
  ],
  Rajshahi: [
    "Rajshahi Sadar (Paba)",
    "Bagha",
    "Bagmara",
    "Charghat",
    "Durgapur",
    "Godagari",
    "Mohanpur",
    "Puthia",
    "Tanore",
  ],
  Natore: [
    "Natore Sadar",
    "Bagatipara",
    "Baraigram",
    "Gurudaspur",
    "Lalpur",
    "Naldanga",
    "Singra",
  ],
  Naogaon: [
    "Naogaon Sadar",
    "Atrai",
    "Badalgachhi",
    "Dhamoirhat",
    "Manda",
    "Mohadevpur",
    "Niamatpur",
    "Patnitala",
    "Porsha",
    "Raninagar",
    "Sapahar",
  ],
  Joypurhat: [
    "Joypurhat Sadar",
    "Akkelpur",
    "Kalai",
    "Khetlal",
    "Panchbibi",
  ],
  Chapainawabganj: [
    "Chapainawabganj Sadar",
    "Bholahat",
    "Gomastapur",
    "Nachole",
    "Shibganj",
  ],
  Pabna: [
    "Pabna Sadar",
    "Atgharia",
    "Bera",
    "Bhangura",
    "Chatmohar",
    "Faridpur",
    "Ishwardi",
    "Santhia",
    "Sujanagar",
  ],
  Sirajganj: [
    "Sirajganj Sadar",
    "Belkuchi",
    "Chauhali",
    "Kamarkhanda",
    "Kazipur",
    "Raiganj",
    "Shahjadpur",
    "Tarash",
    "Ullapara",
  ],
  Rangpur: [
    "Rangpur Sadar",
    "Badarganj",
    "Gangachara",
    "Kaunia",
    "Mithapukur",
    "Pirgachha",
    "Pirganj",
    "Taraganj",
  ],
  Dinajpur: [
    "Dinajpur Sadar",
    "Birampur",
    "Birganj",
    "Biral",
    "Bochaganj",
    "Chirirbandar",
    "Ghoraghat",
    "Hakimpur",
    "Kaharole",
    "Khansama",
    "Nawabganj",
    "Parbatipur",
    "Phulbari",
  ],
  Thakurgaon: [
    "Thakurgaon Sadar",
    "Baliadangi",
    "Haripur",
    "Pirganj",
    "Ranisankail",
  ],
  Panchagarh: [
    "Panchagarh Sadar",
    "Atwari",
    "Boda",
    "Debiganj",
    "Tetulia",
  ],
  Nilphamari: [
    "Nilphamari Sadar",
    "Dimla",
    "Domar",
    "Jaldhaka",
    "Kishoreganj",
    "Saidpur",
  ],
  Lalmonirhat: [
    "Lalmonirhat Sadar",
    "Aditmari",
    "Hatibandha",
    "Kaliganj",
    "Patgram",
  ],
  Kurigram: [
    "Kurigram Sadar",
    "Bhurungamari",
    "Char Rajibpur",
    "Chilmari",
    "Nageshwari",
    "Phulbari",
    "Rajarhat",
    "Raumari",
    "Ulipur",
  ],
  Gaibandha: [
    "Gaibandha Sadar",
    "Phulchhari",
    "Gobindaganj",
    "Palashbari",
    "Sadullapur",
    "Saghata",
    "Sundarganj",
  ],
  Khulna: [
    "Khulna Sadar (Rupsa/Sonadanga)",
    "Batiaghata",
    "Dacope",
    "Dighalia",
    "Dumuria",
    "Koyra",
    "Paikgachha",
    "Phultala",
    "Terokhada",
  ],
  Jashore: [
    "Jashore Sadar",
    "Abhaynagar",
    "Bagherpara",
    "Chaugachha",
    "Jhikargachha",
    "Keshabpur",
    "Manirampur",
    "Sharsha",
  ],
  Satkhira: [
    "Satkhira Sadar",
    "Assasuni",
    "Debhata",
    "Kalaroa",
    "Kaliganj",
    "Shyamnagar",
    "Tala",
  ],
  Bagerhat: [
    "Bagerhat Sadar",
    "Chitalmari",
    "Fakirhat",
    "Kachua",
    "Mollahat",
    "Mongla",
    "Morrelganj",
    "Rampal",
    "Sarankhola",
  ],
  Jhenaidah: [
    "Jhenaidah Sadar",
    "Harinakunda",
    "Kaliganj",
    "Kotchandpur",
    "Maheshpur",
    "Shailkupa",
  ],
  Chuadanga: [
    "Chuadanga Sadar",
    "Alamdanga",
    "Damurhuda",
    "Jibannagar",
  ],
  Meherpur: ["Meherpur Sadar", "Gangni"],
  Kushtia: [
    "Kushtia Sadar",
    "Bheramara",
    "Daulatpur",
    "Khoksa",
    "Kumarkhali",
    "Mirpur",
  ],
  Magura: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
  Narail: ["Narail Sadar", "Kalia", "Lohagara"],
  Barishal: [
    "Barishal Sadar",
    "Agailjhara",
    "Babuganj",
    "Bakerganj",
    "Banaripara",
    "Gaurnadi",
    "Hizla",
    "Mehendiganj",
    "Muladi",
    "Wazirpur",
  ],
  Bhola: [
    "Bhola Sadar",
    "Burhanuddin",
    "Char Fasson",
    "Daulatkhan",
    "Lalmohan",
    "Manpura",
    "Tazumuddin",
  ],
  Patuakhali: [
    "Patuakhali Sadar",
    "Bauphal",
    "Dashmina",
    "Dumki",
    "Galachipa",
    "Kalapara",
    "Mirzaganj",
    "Rangabali",
  ],
  Pirojpur: [
    "Pirojpur Sadar",
    "Bhandaria",
    "Kawkhali",
    "Mathbaria",
    "Nazirpur",
    "Nesarabad (Swarupkathi)",
    "Zianagar",
  ],
  Barguna: [
    "Barguna Sadar",
    "Amtali",
    "Bamna",
    "Betagi",
    "Patharghata",
  ],
  Jhalokati: [
    "Jhalokati Sadar",
    "Kathalia",
    "Nalchity",
    "Rajapur",
  ],
  Faridpur: [
    "Faridpur Sadar",
    "Alfadanga",
    "Bhanga",
    "Boalmari",
    "Charbhadrasan",
    "Madhukhali",
    "Nagarkanda",
    "Sadarpur",
    "Saltha",
  ],
  Gopalganj: [
    "Gopalganj Sadar",
    "Kashiani",
    "Kotalipara",
    "Muksudpur",
    "Tungipara",
  ],
  Madaripur: [
    "Madaripur Sadar",
    "Kalkini",
    "Rajoir",
    "Shibchar",
  ],
  Shariatpur: [
    "Shariatpur Sadar",
    "Bhedarganj",
    "Damudya",
    "Gosairhat",
    "Naria",
    "Zanjira",
  ],
  Rajbari: [
    "Rajbari Sadar",
    "Baliakandi",
    "Goalandaghat",
    "Kalukhali",
    "Pangsha",
  ],
  Manikganj: [
    "Manikganj Sadar",
    "Daulatpur",
    "Ghior",
    "Harirampur",
    "Saturia",
    "Shivalaya",
    "Singair",
  ],
  Munshiganj: [
    "Munshiganj Sadar",
    "Gazaria",
    "Lohajang",
    "Sirajdikhan",
    "Srinagar",
    "Tongibari",
  ],
};

/** Upazila options for a district (falls back to an empty list). */
export const getUpazilasForDistrict = (district: string): string[] =>
  BD_UPAZILAS[district] ?? [];
