-- PASTE 2/4 · step 22 — ps_advance_order, as base64
-- Run the four files IN ORDER (01 → 04), one paste each, in the Supabase SQL
-- Editor. Nothing is created until paste 04.
--
-- Why base64 and not the readable migration: the Editor cuts a paste into
-- statements itself, and readable SQL has arrived there mangled before — once
-- executed as SQL (relation "v_zone" does not exist), once stored several times
-- too long. The base64 alphabet holds no semicolon, no quote, no dollar sign and
-- no double dash, so there is nothing for a splitter to cut on, and line breaks
-- inside it do not matter because they are stripped before decoding.
--
-- Payload: the ONE statement from supabase/migrations/202609140007_wallet_cancel_payment_settle.sql
-- that creates ps_advance_order — 3042 characters, md5 b529183b877014f98a72fedd26c1f00a.
-- cancelling a pending wallet order records the payment as rejected, and fulfilment stays gated until the shop verifies.
-- This chunk must land as 4064 base64 characters.

begin;

insert into _mig_paste_chunks (id, seq, body) values ('ps_advance_order', 1, 'Y3JlYXRlIG9yIHJlcGxhY2UgZnVuY3Rpb24gcHNfYWR2YW5jZV9vcmRlcigKICBwX29yZGVyX2lkIHV1aWQsCiAgcF90byBwc19v
cmRlcl9zdGF0dXMsCiAgcF9ub3RlIHRleHQgZGVmYXVsdCBudWxsCikgcmV0dXJucyBvcmRlcnMKbGFuZ3VhZ2UgcGxwZ3NxbCBz
ZWN1cml0eSBkZWZpbmVyIHNldCBzZWFyY2hfcGF0aCA9IHB1YmxpYyBhcyAkJApkZWNsYXJlCiAgdl9vcmRlciBvcmRlcnMlcm93
dHlwZTsKICB2X2Zyb21fcG9zIGludDsKICB2X3RvX3BvcyAgIGludDsKICB2X2lzX2FkbWluIGJvb2xlYW47CiAgdl9zaG9wIHV1
aWQ7CiAgdl9wYXltZW50X3JlamVjdGVkIGJvb2xlYW47CmJlZ2luCiAgdl9pc19hZG1pbiA6PSAoc2VsZWN0IHBzX2lzX2FkbWlu
KCkpOwogIHZfc2hvcCA6PSAoc2VsZWN0IHBzX3ZlbmRvcl9zaG9wKCkpOwoKICBzZWxlY3QgKiBpbnRvIHZfb3JkZXIgZnJvbSBv
cmRlcnMgd2hlcmUgaWQgPSBwX29yZGVyX2lkIGZvciB1cGRhdGU7CiAgaWYgbm90IGZvdW5kIHRoZW4KICAgIHJhaXNlIGV4Y2Vw
dGlvbiAnb3JkZXIgbm90IGZvdW5kJzsKICBlbmQgaWY7CgogIGlmIG5vdCB2X2lzX2FkbWluIHRoZW4KICAgIGlmIHZfc2hvcCBp
cyBudWxsIG9yIHZfb3JkZXIuc2hvcF9pZCBpcyBkaXN0aW5jdCBmcm9tIHZfc2hvcCB0aGVuCiAgICAgIHJhaXNlIGV4Y2VwdGlv
biAnZm9yYmlkZGVuJzsKICAgIGVuZCBpZjsKICAgIGlmIHBfdG8gbm90IGluICgnY29uZmlybWVkJywgJ3ByZXBhcmluZycsICdy
ZWFkeS1mb3ItcGlja3VwJywgJ2NhbmNlbGxlZCcpIHRoZW4KICAgICAgcmFpc2UgZXhjZXB0aW9uICdmb3JiaWRkZW4nOwogICAg
ZW5kIGlmOwogIGVuZCBpZjsKCiAgLS0gUDEgIzg6IGEgYkthc2gvTmFnYWQgb3JkZXIgbWF5IG5vdCBTVEFSVCBGVUxGSUxNRU5U
IGJlZm9yZSB0aGUgc2hvcCBoYXMKICAtLSB2ZXJpZmllZCB0aGUgcGF5bWVudCBpbiBpdHMgb3duIHdhbGxldCAocHNfdmVyaWZ5
X3BheW1lbnQgZmxpcHMKICAtLSBwYXltZW50X3N0YXR1cyB0byAndmVyaWZpZWQnKS4gJ2NvbmZpcm1lZCcgYW5kICdjYW5jZWxs
ZWQnIHN0YXkgbGVnYWwg4oCUCiAgLS0gY2FuY2VsaW5nIHJlbGVhc2VzIHRoZSByZXNlcnZhdGlvbiB2aWEgdHJnX29yZGVyc19y
ZWxlYXNlX29uX2NhbmNlbC4KICBpZiB2X29yZGVyLnBheW1lbnQgaW4gKCdia2FzaCcsICduYWdhZCcpCiAgICAgYW5kIHZfb3Jk
ZXIucGF5bWVudF9zdGF0dXMgPSAncGVuZGluZ192ZXJpZmljYXRpb24nCiAgICAgYW5kIHBfdG8gaW4gKCdwcmVwYXJpbmcnLCAn
cmVhZHktZm9yLXBpY2t1cCcsICdjb3VyaWVyLWFzc2lnbmVkJywgJ291dC1mb3ItZGVsaXZlcnknLCAnZGVsaXZlcmVkJykgdGhl
bgogICAgcmFpc2UgZXhjZXB0aW9uICdwYXltZW50IG5vdCB2ZXJpZmllZCc7CiAgZW5kIGlmOwoKICAtLSBsZWdhbCBtb3Zlcwog
IGlmIHZfb3JkZXIuc3RhdHVzID0gcF90byB0aGVuCiAgICByZXR1cm4gdl9vcmRlcjsgICAgICAgICAgICAgICAgICAgICAgICAg
IC0tIGlkZW1wb3RlbnQKICBlbmQgaWY7CiAgaWYgcF90byA9ICdjYW5jZWxsZWQnIHRoZW4KICAgIGlmIHZfb3JkZXIuc3RhdHVz
IG5vdCBpbiAoJ3BlbmRpbmcnLCAnY29uZmlybWVkJywgJ3ByZXBhcmluZycpIHRoZW4KICAgICAgcmFpc2UgZXhjZXB0aW9uICdj
YW5ub3QgY2FuY2VsIGZyb20gJScsIHZfb3JkZXIuc3RhdHVzOwogICAgZW5kIGlmOwogIGVsc2UKICAgIHNlbGVjdCBwb3NpdGlv
biBpbnRvIHZfZnJvbV9wb3MgZnJvbSBwc19vcmRlcl9mbG93IHdoZXJlIHN0YXR1cyA9IHZfb3JkZXIuc3RhdHVzOwogICAgc2Vs
ZWN0IHBvc2l0aW9uIGludG8gdl90b19wb3MgICBmcm9tIHBzX29yZGVyX2Zsb3cgd2hlcmUgc3RhdHVzID0gcF90bzsKICAgIGlm
IHZfdG9fcG9zIGlzIG51bGwgb3Igdl9mcm9tX3BvcyBpcyBudWxsIG9yIHZfdG9fcG9zIDw+IHZfZnJvbV9wb3MgKyAxIHRoZW4K
ICAgICAgcmFpc2UgZXhjZXB0aW9uICdpbGxlZ2FsIHRyYW5zaXRpb24gJSAtPiAlJywgdl9vcmRlci5zdGF0dXMsIHBfdG87CiAg
ICBlbmQgaWY7CiAgZW5kIGlmOwoKICAtLSBQMSAjOCAoMik6IGEgY2FuY2VsbGVkIHdhbGxldCBvcmRlcidzIHBheW1lbnQgaXMg
c2V0dGxlZCBhcyBSRUpFQ1RFRCDigJQKICAtLSB0aGUgY3VzdG9tZXIncyB0cmFjayBwYWdlIHNheXMgIm5vdCBhY2NlcHRlZCIs
IG5ldmVyICJ1bmRlcgogIC0tIHZlcmlmaWNhdGlvbiIgb24gYSBjYW5jZWxsZWQgb3JkZXIuCiAgdl9wYXltZW50X3JlamVjdGVk
IDo9IHBfdG8gPSAnY2FuY2VsbGVkJwogICAgYW5kIHZfb3JkZXIucGF5bWVudCBpbiAoJ2JrYXNoJywgJ25hZ2FkJykKICAgIGFu
ZCB2X29yZGVyLnBheW1lbnRfc3RhdHVzID0gJ3BlbmRpbmdfdmVyaWZpY2F0aW9uJzsKCiAgdXBkYXRlIG9yZGVycwogIHNldCBz
dGF0dXMgPSBwX3RvLAogICAgICBwYXltZW50X3N0YXR1cyA9IGNhc2Ugd2hlbiB2X3BheW1lbnRfcmVqZWN0ZWQgdGhlbiAncmVq
ZWN0ZWQnIGVsc2UgcGF5bWVudF9zdGF0dXMgZW5kLAogICAgICBwYXltZW50X3ZlcmlmaWVkX2F0ID0gY2FzZSB3aGVuIHZfcGF5
bWVudF9yZWplY3RlZCB0aGVuIG5vdygpIGVsc2UgcGF5bWVudF92ZXJpZmllZF9hdCBlbmQsCiAgICAgIHVwZGF0ZWRfYXQgPSBu
b3coKQogIHdoZXJlIGlkID0gcF9vcmRlcl9pZDsKICBpbnNlcnQgaW50byBvcmRlcl9zdGF0dXNfaGlzdG9yeSAob3JkZXJfaWQs
IHN0YXR1cywgbm90ZSwgY2hhbmdlZF9ieSkKICB2YWx1ZXMgKHBfb3JkZXJfaWQsIHBfdG8sIHBfbm90ZSwgYXV0aC51aWQoKSk7
CiAgaWYgdl9wYXltZW50X3JlamVjdGVkIHRoZW4KICAgIGluc2VydCBpbnRvIG9yZGVyX3N0YXR1c19oaXN0b3J5IChvcmRlcl9p
ZCwgc3RhdHVzLCBub3RlLCBjaGFuZ2VkX2J5KQogICAgdmFsdWVzIChwX29yZGVyX2lkLCBwX3RvLAogICAgICAnUGF5bWVudCBy
ZWplY3RlZCDigJQgb3JkZXIgY2FuY2VsbGVkIChyZWZ1bmQgZnJvbSB0aGUgc2hvcCB3YWxsZXQsIG9mZmxpbmUpJywKICAgICAg
YXV0aC51aWQoKSk7CiAgZW5kIGlmOwogIHJldHVybiB2X29yZGVyOwplbmQgJCQ7')
on conflict (id, seq) do update set body = excluded.body;  -- re-pasting is safe

commit;

select id, seq, length(regexp_replace(body, '[^A-Za-z0-9+/=]', '', 'g')) as b64_chars from _mig_paste_chunks order by id, seq;
-- expect ps_rider_deliver/1=3104, ps_advance_order/1=4064
