-- PASTE 3/4 · step 22 — ps_verify_payment, as base64
-- Run the four files IN ORDER (01 → 04), one paste each, in the Supabase SQL
-- Editor. Nothing is created until paste 04.
--
-- Why base64 and not the readable migration: the Editor cuts a paste into
-- statements itself, and readable SQL has arrived there mangled before — once
-- executed as SQL (relation "v_zone" does not exist), once stored several times
-- too long. The base64 alphabet holds no semicolon, no quote, no dollar sign and
-- no double dash, so there is nothing for a splitter to cut on, and line breaks
-- inside it do not matter because they are stripped before decoding.
--
-- Payload: the ONE statement from supabase/migrations/202609140007_wallet_cancel_payment_settle.sql
-- that creates ps_verify_payment — 2736 characters, md5 2b72524d2cff36383dbe9c08be34d572.
-- the shop Verify / Reject decision — reject cancels the order and releases the stock.
-- This chunk must land as 3656 base64 characters.

begin;

insert into _mig_paste_chunks (id, seq, body) values ('ps_verify_payment', 1, 'Y3JlYXRlIG9yIHJlcGxhY2UgZnVuY3Rpb24gcHNfdmVyaWZ5X3BheW1lbnQocF9vcmRlcl9pZCB1dWlkLCBwX2FjdGlvbiB0ZXh0
LCBwX25vdGUgdGV4dCBkZWZhdWx0IG51bGwpCnJldHVybnMgb3JkZXJzCmxhbmd1YWdlIHBscGdzcWwgc2VjdXJpdHkgZGVmaW5l
ciBzZXQgc2VhcmNoX3BhdGggPSBwdWJsaWMgYXMgJCQKZGVjbGFyZQogIHZfb3JkZXIgb3JkZXJzJXJvd3R5cGU7CiAgdl9pc19h
ZG1pbiBib29sZWFuOwogIHZfc2hvcCB1dWlkOwpiZWdpbgogIHZfaXNfYWRtaW4gOj0gKHNlbGVjdCBwc19pc19hZG1pbigpKTsK
ICB2X3Nob3AgOj0gKHNlbGVjdCBwc192ZW5kb3Jfc2hvcCgpKTsKCiAgc2VsZWN0ICogaW50byB2X29yZGVyIGZyb20gb3JkZXJz
IHdoZXJlIGlkID0gcF9vcmRlcl9pZCBmb3IgdXBkYXRlOwogIGlmIG5vdCBmb3VuZCB0aGVuCiAgICByYWlzZSBleGNlcHRpb24g
J29yZGVyIG5vdCBmb3VuZCc7CiAgZW5kIGlmOwoKICAtLSBTYW1lIGF1dGggbW9kZWwgYXMgcHNfYWR2YW5jZV9vcmRlcjogc3Rh
ZmYgb3IgdGhlIG93bmluZyBzaG9wLgogIGlmIG5vdCB2X2lzX2FkbWluIHRoZW4KICAgIGlmIHZfc2hvcCBpcyBudWxsIG9yIHZf
b3JkZXIuc2hvcF9pZCBpcyBkaXN0aW5jdCBmcm9tIHZfc2hvcCB0aGVuCiAgICAgIHJhaXNlIGV4Y2VwdGlvbiAnZm9yYmlkZGVu
JzsKICAgIGVuZCBpZjsKICBlbmQgaWY7CgogIGlmIHZfb3JkZXIucGF5bWVudCA9ICdjb2QnIHRoZW4KICAgIHJhaXNlIGV4Y2Vw
dGlvbiAnbm90IGEgd2FsbGV0IHBheW1lbnQnOwogIGVuZCBpZjsKICBpZiB2X29yZGVyLnBheW1lbnRfc3RhdHVzIDw+ICdwZW5k
aW5nX3ZlcmlmaWNhdGlvbicgdGhlbgogICAgcmFpc2UgZXhjZXB0aW9uICdwYXltZW50IGFscmVhZHkgZGVjaWRlZCc7CiAgZW5k
IGlmOwoKICAtLSBQMSAjOCAoMik6IGEgY2FuY2VsbGVkIG9yZGVyIGNhbiBuZXZlciBiZSBWRVJJRklFRCDigJQgdGhlIG9yZGVy
IGlzIG92ZXIsCiAgLS0gdGhlIG1vbmV5IGlzIG5vdCBpbi4gUm93cyBjYW5jZWxsZWQgQkVGT1JFIHRoZSBhdXRvLXJlamVjdCBy
dWxlIHN0aWxsCiAgLS0gbmVlZCBhIGRlY2lzaW9uLCBzbyBSRUpFQ1Qgc3RheXMgbGVnYWwgYW5kIHNldHRsZXMgdGhlbSAocmUt
c2V0dGluZwogIC0tIHN0YXR1cz0nY2FuY2VsbGVkJyBpcyBhIG5vLW9wOiB0aGUgcmVsZWFzZSB0cmlnZ2VyIG9ubHkgZmlyZXMg
b24gdGhlCiAgLS0gdHJhbnNpdGlvbiBpbnRvIGNhbmNlbGxlZCwgc28gc3RvY2sgY2Fubm90IGJlIHJlbGVhc2VkIHR3aWNlKS4K
ICBpZiB2X29yZGVyLnN0YXR1cyA9ICdjYW5jZWxsZWQnIGFuZCBwX2FjdGlvbiA9ICd2ZXJpZmllZCcgdGhlbgogICAgcmFpc2Ug
ZXhjZXB0aW9uICdvcmRlciBhbHJlYWR5IGNhbmNlbGxlZCc7CiAgZW5kIGlmOwoKICBpZiBwX2FjdGlvbiA9ICd2ZXJpZmllZCcg
dGhlbgogICAgLS0gVGhlIHNob3AgY2hlY2tlZCBpdHMgb3duIGJLYXNoL05hZ2FkIHdhbGxldDogdGhlIG1vbmV5IGlzIGluLCB0
aGlzIGlzCiAgICAtLSB0aGUgbW9tZW50IHRoZSBvcmRlciBtYXkgc3RhcnQgZnVsZmlsbWVudC4KICAgIHVwZGF0ZSBvcmRlcnMK
ICAgIHNldCBwYXltZW50X3N0YXR1cyA9ICd2ZXJpZmllZCcsIHBheW1lbnRfdmVyaWZpZWRfYXQgPSBub3coKSwgdXBkYXRlZF9h
dCA9IG5vdygpCiAgICB3aGVyZSBpZCA9IHBfb3JkZXJfaWQ7CiAgICBpbnNlcnQgaW50byBvcmRlcl9zdGF0dXNfaGlzdG9yeSAo
b3JkZXJfaWQsIHN0YXR1cywgbm90ZSwgY2hhbmdlZF9ieSkKICAgIHZhbHVlcyAocF9vcmRlcl9pZCwgdl9vcmRlci5zdGF0dXMs
CiAgICAgIHVwcGVyKGxlZnQodl9vcmRlci5wYXltZW50LCAxKSkgfHwgcmlnaHQodl9vcmRlci5wYXltZW50LCBsZW5ndGgodl9v
cmRlci5wYXltZW50KSAtIDEpIHx8ICcgcGF5bWVudCB2ZXJpZmllZCcsCiAgICAgIGF1dGgudWlkKCkpOwogIGVsc2lmIHBfYWN0
aW9uID0gJ3JlamVjdGVkJyB0aGVuCiAgICAtLSBObyBtYXRjaGluZyBtb25leSBpbiB0aGUgd2FsbGV0OiB0aGUgb3JkZXIgaXMg
Y2FuY2VsbGVkIGFuZCB0aGUKICAgIC0tIHJlc2VydmF0aW9uIGdvZXMgYmFjayB0byB0aGUgc2hlbGYgKHRyZ19vcmRlcnNfcmVs
ZWFzZV9vbl9jYW5jZWwpLgogICAgLS0gVGhlIHJlZnVuZCB0byB0aGUgY3VzdG9tZXIncyB3YWxsZXQgaXMgdGhlIHNob3AncyBv
ZmZsaW5lIGhhbmRsaW5nLgogICAgdXBkYXRlIG9yZGVycwogICAgc2V0IHBheW1lbnRfc3RhdHVzID0gJ3JlamVjdGVkJywgcGF5
bWVudF92ZXJpZmllZF9hdCA9IG5vdygpLAogICAgICAgIHN0YXR1cyA9ICdjYW5jZWxsZWQnLCB1cGRhdGVkX2F0ID0gbm93KCkK
ICAgIHdoZXJlIGlkID0gcF9vcmRlcl9pZDsKICAgIGluc2VydCBpbnRvIG9yZGVyX3N0YXR1c19oaXN0b3J5IChvcmRlcl9pZCwg
c3RhdHVzLCBub3RlLCBjaGFuZ2VkX2J5KQogICAgdmFsdWVzIChwX29yZGVyX2lkLCAnY2FuY2VsbGVkJywKICAgICAgJ1BheW1l
bnQgcmVqZWN0ZWQnIHx8IGNvYWxlc2NlKCcg4oCUICcgfHwgdHJpbShjb2FsZXNjZShwX25vdGUsICcnKSksICcnKSB8fAogICAg
ICAnIChyZWZ1bmQgZnJvbSB0aGUgc2hvcCB3YWxsZXQsIG9mZmxpbmUpJywKICAgICAgYXV0aC51aWQoKSk7CiAgZWxzZQogICAg
cmFpc2UgZXhjZXB0aW9uICd1bmtub3duIHBheW1lbnQgYWN0aW9uJzsKICBlbmQgaWY7CgogIHJldHVybiAoc2VsZWN0ICogZnJv
bSBvcmRlcnMgd2hlcmUgaWQgPSBwX29yZGVyX2lkKTsKZW5kICQkOw==')
on conflict (id, seq) do update set body = excluded.body;  -- re-pasting is safe

commit;

select id, seq, length(regexp_replace(body, '[^A-Za-z0-9+/=]', '', 'g')) as b64_chars from _mig_paste_chunks order by id, seq;
-- expect ps_rider_deliver/1=3104, ps_advance_order/1=4064, ps_verify_payment/1=3656
