-- PASTE 19/23 · 19_realtime_offers-ps_checkout_health-chunk-1-3.sql
-- Source: supabase/migrations/202609250007_realtime_offers.sql
-- Base64 chunk — copy the WHOLE insert; nothing may be dropped.
-- Repeat-safe: re-running any part is harmless.
begin;

create table if not exists _mig_paste_chunks (
  id   text not null,
  seq  int  not null,
  body text not null,
  primary key (id, seq)
);
alter table _mig_paste_chunks enable row level security;
drop policy if exists "paste chunks" on _mig_paste_chunks;
create policy "paste chunks" on _mig_paste_chunks for all using (true) with check (true);
delete from _mig_paste_chunks where id = 'ps_checkout_health';  -- a re-run starts clean

insert into _mig_paste_chunks (id, seq, body) values ('ps_checkout_health', 1,
'Y3JlYXRlIG9yIHJlcGxhY2UgZnVuY3Rpb24gcHNfY2hlY2tvdXRfaGVhbHRoKCkKcmV0dXJucyBqc29uYgpsYW5ndWFnZSBzcWwKc3RhYmxlCnNlY3VyaXR5IGRlZmluZXIKc2V0IHNlYXJjaF9wYXRoID0gcHVibGljCmFzICQkCiAgc2VsZWN0IGpzb25iX2J1aWxkX29iamVjdCgKICAgICd2ZXJzaW9uJywgJzIwMjYwOTI1MDAwNycsCiAgICAnZ2lmdF93cmFwX251bGxhYmxlJywgY29hbGVzY2UoKAogICAgICBzZWxlY3QgYy5pc19udWxsYWJsZSA9ICdZRVMnCiAgICAgIGZyb20gaW5mb3JtYXRpb25fc2NoZW1hLmNvbHVtbnMgYwogICAgICB3aGVyZSBjLnRhYmxlX3NjaGVtYSA9ICdwdWJsaWMnIGFuZCBjLnRhYmxlX25hbWUgPSAnb3JkZXJzJyBhbmQgYy5jb2x1bW5fbmFtZSA9ICdnaWZ0X3dyYXAnCiAgICApLCB0cnVlKSwKICAgICd0b3RhbHNfZ3VhcmRfY3VycmVudCcsIGV4aXN0cyAoCiAgICAgIHNlbGVjdCAxIGZyb20gcGdfcHJvYyBwIGpvaW4gcGdfbmFtZXNwYWNlIG4gb24gbi5vaWQgPSBwLnByb25hbWVzcGFjZQogICAgICB3aGVyZSBuLm5zcG5hbWUgPSAncHVibGljJyBhbmQgcC5wcm9uYW1lID0gJ3BzX2NoZWNrX29yZGVyX3RvdGFscycKICAgICAgICBhbmQgcC5wcm9zcmMgbGlrZSAnJWdpZnRfZmVlJScKICAgICksCiAgICAnaW5zZXJ0X2d1YXJkX2N1cnJlbnQnLCBleGlzdHMgKAogICAgICBzZWxlY3QgMSBmcm9tIHBnX3Byb2MgcCBqb2luIHBnX25hbWVzcGFjZSBuIG9uIG4ub2lkID0gcC5wcm9uYW1lc3BhY2UKICAgICAgd2hlcmUgbi5uc3BuYW1lID0gJ3B1YmxpYycgYW5kIHAucHJvbmFtZSA9ICdwc19jaGVja19vcmRlcl9pbnNlcnQnCiAgICAgICAgYW5kIHAucHJvc3JjIGxpa2UgJyVia2FzaCUnCiAgICApLAogICAgJ3N0YXR1c191cGRhdGVfb2snLCBleGlzdHMgKAogICAgICBzZWxlY3QgMSBmcm9tIHBnX3Byb2MgcCBqb2luIHBnX25hbWVzcGFjZSBuIG9uIG4ub2lkID0gcC5wcm9uYW1lc3BhY2UKICAgICAgd2hlcmUgbi5uc3BuYW1lID0gJ3B1YmxpYycgYW5kIHAucHJvbmFtZSA9ICdwc193cml0ZV9zaG9wX2xlZGdlcicKICAgICAgICBhbmQgcC5wcm9zcmMgbGlrZSAnJW9sZC5zdGF0dXMgaXMgZGlzdGluY3QgZnJvbSBuZXcuc3RhdHVzJScKICAgICksCiAgICAncGF5bWVudF92ZXJpZnlfb2snLCBleGlzdHMgKAogICAgICBzZWxlY3QgMSBmcm9tIHBnX3Byb2MgcCBqb2luIHBnX25hbWVzcGFjZSBuIG9uIG4ub2lkID0gcC5wcm9uYW1lc3BhY2UKICAgICAgd2hlcmUgbi5uc3BuYW1lID0gJ3B1YmxpYycgYW5kIHAucHJvbmFtZSA9ICdwc192ZXJpZnlfcGF5bWVudCcKICAgICAgICBhbmQgcC5wcm9zcmMgbGlrZSAnJXNlbGVjdCAqIGludG8gdl9vcmRlciBmcm9tIG9yZGVycyB3aGVyZSBpZCA9IHBfb3JkZXJfaWQ7JScKICAgICksCiAgICAncmlkZXJfZ3VhcmRfb2snLCBleGlzdHMgKAogICAgICBzZWxlY3QgMSBmcm9tIHBnX3Byb2MgcCBqb2luIHBnX25hbWVzcGFjZSBuIG9uIG4ub2lkID0gcC5wcm9uYW1lc3BhY2UKICAgICAgd2hlcmUgbi5uc3BuYW1lID0gJ3B1YmxpYycgYW5kIHAucHJvbmFtZSA9ICdwc19ndWFyZF9yaWRlcl9zZWxmX3VwZGF0ZScKICAgICAgICBhbmQgcC5wcm9zcmMgbGlrZSAnJWN1cnJlbnRfdXNlciBub3QgaW4lJwogICAgKSwKICAgICdwYXltZW50X21ldGhvZHNfd2lkZW5lZCcsIGV4aXN0cyAoCiAgICAgIHNlbGVjdCAxIGZyb20gcGdfY29uc3RyYWludCBrCiAgICAgIHdoZXJlIGsuY29ucmVsaWQgPSAncHVibGljLm9yZGVycyc6OnJlZ2NsYXNzIGFuZCBrLmNvbm5hbWUgPSAnb3JkZXJzX3BheW1lbnRfY2hlY2snCiAgICAgICAgYW5kIHBnX2dldF9jb25zdHJhaW50ZGVmKGsub2lkKSBsaWtlICclYmthc2glJwogICAgKSwKICAgICdwbGFjZV9vcmRlcl9ycGMnLCBleGlzdHMgKAogICAgICBzZWxlY3QgMSBmcm9tIHBnX3Byb2MgcCBqb2luIHBnX25hbWVzcGFjZSBuIG9uIG4ub2lkID0gcC5wcm9uYW1lc3BhY2UKICAgICAgd2hlcmUgbi5uc3BuYW1lID0gJ3B1YmxpYycgYW5kIHAucHJvbmFtZSA9ICdwc19wbGFjZV9vcmRlcicKICAgICksCiAgICAncnBjX2dyYW50c19sb2NrZWQnLCBub3QgZXhpc3RzICgKICAgICAg');

commit;
